#CP
CP_SOLVERS = ['gecode', 'chuffed']#'gist'

OPTIMAL_CASE = 1
SUB_OPTIMAL_CASE = 2
NO_SOLUTION = 0

SYMMETRY_BREAKING = 1
NO_SYMMETRY_BREAKING = 0
SIM_LIST = [SYMMETRY_BREAKING,NO_SYMMETRY_BREAKING]
SIMMETRY_BREAK_STRING = "_symbreak"
